on:
  push:
    branches:
        - "main"
jobs:
    lab-job:
        run-ons: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'Hello DevOps'   
jobs:
    lab-job:
        run-ons: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'Hello DevOps'
            - name: Second Step
              run: echo 'This is second step'
  jobs:
    lab-job:
        run-ons: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'Hello DevOps'
            - name: Second Step
              run: echo 'This is second step'
    second-job:
        run-ons: ubuntu-latest
        steps:
            - name: Start Second job
              run: echo 'Hello Second Job'
